WARNING 2025-06-29 16:19:16,051 views 5112 18356 Failed login attempt for IP 127.0.0.1: {'email': [ErrorDetail(string='Enter a valid email address.', code='invalid')]}
WARNING 2025-06-29 16:19:16,057 views 5112 7540 Failed login attempt for IP 127.0.0.1: {'email': [ErrorDetail(string='Enter a valid email address.', code='invalid')]}
WARNING 2025-06-29 16:19:16,062 views 5112 16892 Failed login attempt for IP 127.0.0.1: {'email': [ErrorDetail(string='Enter a valid email address.', code='invalid')]}
WARNING 2025-06-29 16:19:16,066 views 5112 7796 Failed login attempt for IP 127.0.0.1: {'email': [ErrorDetail(string='Enter a valid email address.', code='invalid')]}
WARNING 2025-06-29 16:19:16,071 views 5112 19048 Failed login attempt for IP 127.0.0.1: {'email': [ErrorDetail(string='Enter a valid email address.', code='invalid')]}
WARNING 2025-06-29 16:20:31,929 views 5112 9228 Login rate limit exceeded for IP 127.0.0.1
WARNING 2025-06-29 16:20:32,544 views 5112 10648 Invalid super admin login attempt from IP 127.0.0.1 for email admin@example.com
WARNING 2025-06-29 16:20:33,162 views 5112 10188 Invalid super admin login attempt from IP 127.0.0.1 for email nonexistent@example.com
WARNING 2025-06-29 16:20:33,804 views 5112 15508 Invalid super admin login attempt from IP 127.0.0.1 for email admin@example.com
WARNING 2025-06-29 16:20:34,075 views 5112 4856 Login rate limit exceeded for IP 127.0.0.1
WARNING 2025-06-29 16:20:34,079 views 5112 15900 Login rate limit exceeded for IP 127.0.0.1
WARNING 2025-06-29 16:20:34,083 views 5112 4928 Login rate limit exceeded for IP 127.0.0.1
WARNING 2025-06-29 16:20:34,087 views 5112 14936 Login rate limit exceeded for IP 127.0.0.1
WARNING 2025-06-29 16:20:44,403 views 6652 16916 OTP verification failed for test2@example.com - 2 attempts remaining
WARNING 2025-06-29 16:20:44,403 views 6652 16916 OTP verification failed for test3@example.com - 2 attempts remaining
WARNING 2025-06-29 16:20:44,404 views 6652 16916 OTP verification failed for test3@example.com - 1 attempts remaining
WARNING 2025-06-29 16:20:44,404 views 6652 16916 OTP verification failed for test3@example.com - 0 attempts remaining
WARNING 2025-06-29 16:20:44,405 views 6652 16916 OTP verification failed - too many attempts for test3@example.com
WARNING 2025-06-29 16:22:30,257 views 2860 10472 OTP verification failed for test2@example.com - 2 attempts remaining
WARNING 2025-06-29 16:22:30,258 views 2860 10472 OTP verification failed for test3@example.com - 2 attempts remaining
WARNING 2025-06-29 16:22:30,259 views 2860 10472 OTP verification failed for test3@example.com - 1 attempts remaining
WARNING 2025-06-29 16:22:30,259 views 2860 10472 OTP verification failed for test3@example.com - 0 attempts remaining
WARNING 2025-06-29 16:22:30,260 views 2860 10472 OTP verification failed - too many attempts for test3@example.com
WARNING 2025-06-29 16:22:40,708 views 5112 9140 Login rate limit exceeded for IP 127.0.0.1
WARNING 2025-06-29 16:22:40,713 views 5112 18504 Super admin login rate limit exceeded for IP 127.0.0.1
WARNING 2025-06-29 16:22:40,718 views 5112 19072 Super admin login rate limit exceeded for IP 127.0.0.1
WARNING 2025-06-29 16:22:40,723 views 5112 15164 Super admin login rate limit exceeded for IP 127.0.0.1
WARNING 2025-06-29 16:22:40,972 views 5112 17336 Login rate limit exceeded for IP 127.0.0.1
WARNING 2025-06-29 16:22:40,976 views 5112 15884 Login rate limit exceeded for IP 127.0.0.1
WARNING 2025-06-29 16:22:40,980 views 5112 10092 Login rate limit exceeded for IP 127.0.0.1
WARNING 2025-06-29 16:22:40,984 views 5112 7500 Login rate limit exceeded for IP 127.0.0.1
WARNING 2025-06-29 16:24:11,942 views 5112 14924 Login rate limit exceeded for IP 127.0.0.1
WARNING 2025-06-29 16:24:11,958 views 5112 18272 Login rate limit exceeded for IP 127.0.0.1
WARNING 2025-06-29 16:26:16,588 views 5112 18100 Login rate limit exceeded for IP 127.0.0.1
WARNING 2025-06-29 16:26:16,609 views 5112 2572 Login rate limit exceeded for IP 127.0.0.1
WARNING 2025-06-29 16:26:16,625 views 5112 4232 Login rate limit exceeded for IP 127.0.0.1
WARNING 2025-06-29 16:26:16,626 views 5112 2092 Login rate limit exceeded for IP 127.0.0.1
WARNING 2025-06-29 16:26:16,641 views 5112 14404 Login rate limit exceeded for IP 127.0.0.1
ERROR 2025-06-29 20:51:57,405 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:57,676 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:57,691 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:57,705 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:57,720 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:57,735 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:57,750 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:57,764 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:57,779 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:57,793 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:57,808 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:57,823 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:57,838 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:57,854 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:57,869 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:57,884 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:57,899 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:57,916 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:57,932 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:57,946 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:57,962 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:57,977 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:58,020 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:58,035 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:58,050 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:58,066 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:58,086 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:58,101 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:58,116 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:58,131 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:58,145 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:58,161 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:58,175 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:58,190 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:58,206 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:58,221 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:58,235 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:58,252 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:58,836 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:58,851 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:58,867 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:58,883 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 20:51:58,900 exception 20288 18300 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:44,594 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:44,823 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:44,838 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:44,852 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:44,866 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:44,880 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:44,894 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:44,908 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:44,923 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:44,938 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:44,953 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:44,967 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:44,981 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:44,997 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,013 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,028 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,041 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,056 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,070 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,085 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,099 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,114 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,153 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,167 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,181 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,195 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,215 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,229 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,244 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,258 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,272 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,286 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,300 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,314 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,328 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,342 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,356 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,371 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,945 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,960 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,975 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:45,990 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:06:46,004 exception 9428 19776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:11:44,627 exception 20056 11716 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:11:44,862 exception 20056 11716 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:11:44,878 exception 20056 11716 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:11:44,893 exception 20056 11716 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:11:44,906 exception 20056 11716 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:11:44,921 exception 20056 11716 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:11:44,935 exception 20056 11716 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:11:44,949 exception 20056 11716 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:11:44,964 exception 20056 11716 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:11:44,979 exception 20056 11716 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:11:44,993 exception 20056 11716 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:11:45,008 exception 20056 11716 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:11:45,023 exception 20056 11716 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:12:47,982 exception 3536 21024 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:12:48,219 exception 3536 21024 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:12:48,236 exception 3536 21024 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:12:48,250 exception 3536 21024 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:12:48,264 exception 3536 21024 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:12:48,278 exception 3536 21024 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:12:48,292 exception 3536 21024 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:12:48,306 exception 3536 21024 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:12:48,321 exception 3536 21024 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:12:48,336 exception 3536 21024 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:12:48,350 exception 3536 21024 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:12:48,364 exception 3536 21024 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:12:48,379 exception 3536 21024 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:12:48,398 exception 3536 21024 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:12:48,413 exception 3536 21024 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-06-29 21:12:48,427 exception 3536 21024 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\samip\OneDrive\Desktop\prs\PRS\Backend_PRS-1\.venv\Lib\site-packages\django\http\request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
